version: "3"
services:
  nginx:
    ports:
      - "3000:80"

  node-app:
    ports:
      - "4001:3000"
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=pulkit
      - MONGO_PASSWORD=pulkit
      - SESSION_SECRET=secret
    command: npm run dev

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pulkit
      - MONGO_INITDB_ROOT_PASSWORD=pulkit
