version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  node-app:
    build: .
    image: pulkitsinyal/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pulkit
      - MONGO_INITDB_ROOT_PASSWORD=pulkit
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
